name: efficient_school
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  firebase_core: ^3.2.0
  cloud_firestore: ^5.1.0
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  firebase_storage: ^12.1.1
  file_picker: ^8.0.6
  cached_network_image: ^3.3.1
  intl: ^0.19.0
  readmore: ^3.0.0
  shimmer: ^3.0.0
  carousel_slider: ^4.2.1
  video_player: ^2.9.1
  video_thumbnail: ^0.5.3
  font_awesome_flutter: ^10.7.0
  smooth_page_indicator: ^1.2.0+3
  shared_preferences: ^2.2.3
  fluttertoast: ^8.2.6
  provider: ^6.1.2
  flutter_blurhash: ^0.8.2
  lottie: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/animation/
